[package]
name = "tauri-notes-dev-tools"
edition = "2021"

[dependencies]
rocket = "0.5.1"
juniper_rocket = "0.9.0"

[dependencies.tauri-notes]
path = "../src-tauri"

[[bin]]
name = "generate_sdl"
path = "src/bin/generate_sdl.rs"

[[bin]]
name = "dev_server"
path = "src/bin/dev_server.rs"
